apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: thetillhoff-de-http
spec:
  parentRefs:
  - name: http-gateway
    namespace: gateways
  hostnames:
  - thetillhoff.de
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
