apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: thetillhoff-de
spec:
  parentRefs:
  - name: https-gateway-thetillhoff-de
    namespace: gateways
  hostnames:
  - thetillhoff.de
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: thetillhoff-de
      port: 80
