name: Validate Pulumi changes

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "pulumi/**"
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: pulumi/package.json
          cache: 'npm'
      - run: npm ci

      - run: pulumi preview
        working-directory: ./pulumi

  plan:
    needs: preview
    runs-on: ubuntu-24.04
    concurrency: pulumi-state
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: pulumi/package.json
          cache: 'npm'
      - run: npm ci

      - run: pulumi preview
        working-directory: ./pulumi
